# url : "https://harookie.github.io"
# baseurl : "https://harookie.github.io"
# remote_theme: samarsault/plainwhite-jekyll
# theme: jekyll-theme-architect

permalink: /:title

theme: jekyll-theme-minimal