@startuml "3G_MOD_ERP"
box "TANGO" #lightblue
    participant controller
    database dr_db
    database im_db
    queue queue
    participant biz_process
    participant datasync
end box
box "CMS"
    participant CMS
end box

queue <- biz_process: Queue listen
queue <- datasync: Queue listen
autonumber
controller ->  dr_db: 작업 조회
activate dr_db
return 작업 리턴
controller -> queue: 작업 할당
queue -> biz_process: GET 작업
activate biz_process
im_db <- biz_process: 대사 결과 쓰기
dr_db <- biz_process: 작업 결과 쓰기
deactivate biz_process
controller ->  dr_db: 작업 조회
activate dr_db
return 작업 리턴
controller -> queue: 작업 할당
queue -> datasync: GET 작업
datasync -> CMS: 결과 파일 생성
dr_db <- datasync: 결과 쓰기
@enduml